export const APP_FETCH_DATA_START = 'FETCH_DATA_START';
export const APP_FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const APP_FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const APP_CHANGE_LANG = 'APP_CHANGE_LANG'