export const APP_FETCH_DATA_START = 'APP_FETCH_DATA_START';
export const APP_FETCH_DATA_SUCCESS = 'APP_FETCH_DATA_SUCCESS';
export const APP_FETCH_DATA_ERROR = 'APP_FETCH_DATA_ERROR';
export const APP_CHANGE_LANG = 'APP_CHANGE_LANG';
export const APP_CHANGE_THEME = 'APP_CHANGE_THEME';
